import Sidebar from "@/components/sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import Searchbox from "@/components/searchbox";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TUFF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <section className="flex w-screen">
          <Sidebar />
          <section className="w-full flex flex-col ml-15">
            <Searchbox />
            {/* CONTINUE FROM HERE */}

            {children}
          </section>
        </section>
      </body>
    </html>
  );
}
