import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope();

export const metadata = {
  title: "TUFF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
